"""Computer Use 的公开契约入口。"""

from .backend import ComputerUseBackend
from .backends import CuaDriverBackend, FakeBackend, FakeCall, NoopBackend
from .contracts import (
    ActionEffect,
    ActionResult,
    AppInfo,
    CaptureMode,
    CaptureResult,
    ComputerUseAction,
    ComputerUseExecutor,
    ComputerUseResult,
    DeliveryMode,
    EscalationHint,
    UIElement,
    WindowInfo,
)
from .errors import (
    ActionTimeoutError,
    ActionUnverifiedError,
    ApprovalDeniedError,
    BackendDisconnectedError,
    BackendStartError,
    BackendUnavailableError,
    ComputerUseError,
    DriverNotFoundError,
    InvalidArgumentsError,
    PermissionDeniedError,
    ProtocolError,
    SafetyBlockedError,
    StaleElementError,
    TargetNotFoundError,
)
from .readiness import check_cua_driver_readiness
from .transport import build_cua_driver_env

__all__ = [
    "ComputerUseAction",
    "CaptureMode",
    "DeliveryMode",
    "ActionEffect",
    "UIElement",
    "CaptureResult",
    "AppInfo",
    "WindowInfo",
    "EscalationHint",
    "ActionResult",
    "ComputerUseResult",
    "ComputerUseExecutor",
    "ComputerUseBackend",
    "ComputerUseError",
    "BackendUnavailableError",
    "BackendStartError",
    "BackendDisconnectedError",
    "ActionTimeoutError",
    "InvalidArgumentsError",
    "TargetNotFoundError",
    "StaleElementError",
    "PermissionDeniedError",
    "SafetyBlockedError",
    "ApprovalDeniedError",
    "ActionUnverifiedError",
    "ProtocolError",
    "DriverNotFoundError",
    "CuaDriverBackend",
    "NoopBackend",
    "FakeBackend",
    "FakeCall",
    "build_cua_driver_env",
    "check_cua_driver_readiness",
]
