"""Hermes 配置管理的中立契约、字段目录与应用服务。"""

from .contracts import (
    MAX_CONFIG_PATCH_CHANGES,
    ConfigApplyMode,
    ConfigConflict,
    ConfigFieldDescriptor,
    ConfigFieldReadOnly,
    ConfigFieldSpec,
    ConfigFieldUnknown,
    ConfigInvalid,
    ConfigManagementError,
    ConfigNotFound,
    ConfigPatch,
    ConfigPatchChange,
    ConfigPatchResult,
    ConfigRepository,
    ConfigRepositorySnapshot,
    ConfigRepositoryWriteResult,
    ConfigRevision,
    ConfigShadowed,
    ConfigSnapshot,
    ConfigStoredField,
    ConfigUnavailable,
    ConfigValue,
    ConfigValueInvalid,
    ConfigValueSource,
    ConfigValueType,
    ConfigWriteFailed,
)
from .fields import (
    DEFAULT_CONFIG_FIELD_REGISTRY,
    ConfigFieldRegistry,
)
from .service import ConfigReadService, ConfigWriteService

__all__ = [
    "DEFAULT_CONFIG_FIELD_REGISTRY",
    "MAX_CONFIG_PATCH_CHANGES",
    "ConfigApplyMode",
    "ConfigConflict",
    "ConfigFieldDescriptor",
    "ConfigFieldReadOnly",
    "ConfigFieldRegistry",
    "ConfigFieldSpec",
    "ConfigFieldUnknown",
    "ConfigInvalid",
    "ConfigManagementError",
    "ConfigNotFound",
    "ConfigPatch",
    "ConfigPatchChange",
    "ConfigPatchResult",
    "ConfigReadService",
    "ConfigRepository",
    "ConfigRepositorySnapshot",
    "ConfigRepositoryWriteResult",
    "ConfigRevision",
    "ConfigShadowed",
    "ConfigSnapshot",
    "ConfigStoredField",
    "ConfigUnavailable",
    "ConfigValue",
    "ConfigValueInvalid",
    "ConfigValueSource",
    "ConfigValueType",
    "ConfigWriteFailed",
    "ConfigWriteService",
]
