"""独立 DOCX 创建、读取、搜索、编辑、验证与可选渲染公共接口。"""

from .errors import DocxError
from .models import (
    AppliedEdit,
    AppendParagraph,
    AppendTableRow,
    BlockRemap,
    CreateDocumentRequest,
    CreateDocumentResult,
    DeleteParagraph,
    DeleteTableRow,
    DocumentMetadata,
    DocumentSnapshot,
    DocumentWarning,
    EditDocumentRequest,
    EditDocumentResult,
    FormatTextMatch,
    HeadingSpec,
    InspectDocumentRequest,
    InsertBulletListAfter,
    InsertHyperlinkAfter,
    InsertImageAfter,
    InsertNumberedListAfter,
    InsertParagraphAfter,
    InsertParagraphBefore,
    InsertTableAfter,
    PageBreakSpec,
    ParagraphSnapshot,
    ParagraphSpec,
    ReplaceParagraphText,
    ReplaceTableCellText,
    ReplaceTextMatch,
    SearchDocumentRequest,
    SearchDocumentResult,
    TableCellSnapshot,
    TableSnapshot,
    TableSpec,
    TextMatch,
    TextRunSnapshot,
    TextRunSpec,
    UNSET,
    UpdateParagraphProperties,
    UpdateDocumentMetadata,
    UpdateFooterText,
    UpdateHeaderText,
    UpdatePageSetup,
)
from .reader import DocxReader, inspect_document
from .renderer import (
    DocxRenderer,
    RenderDocumentRequest,
    RenderDocumentResult,
    RenderedPage,
    render_document,
)
from .runtime import DocxRuntimeStatus, RuntimeComponentStatus
from .search import DocxSearcher, search_document
from .editor import DocxEditor, edit_document
from .service import DocxService, create_document
from .validation_models import (
    ValidateDocumentRequest,
    ValidateDocumentResult,
    ValidationIssue,
)
from .validator import DocxValidator, validate_document

__all__ = [
    "AppliedEdit",
    "AppendParagraph",
    "AppendTableRow",
    "BlockRemap",
    "CreateDocumentRequest",
    "CreateDocumentResult",
    "DeleteParagraph",
    "DeleteTableRow",
    "DocumentMetadata",
    "DocumentSnapshot",
    "DocumentWarning",
    "DocxError",
    "DocxEditor",
    "DocxReader",
    "DocxRenderer",
    "DocxRuntimeStatus",
    "DocxSearcher",
    "DocxService",
    "DocxValidator",
    "EditDocumentRequest",
    "EditDocumentResult",
    "FormatTextMatch",
    "HeadingSpec",
    "InspectDocumentRequest",
    "InsertBulletListAfter",
    "InsertHyperlinkAfter",
    "InsertImageAfter",
    "InsertNumberedListAfter",
    "InsertParagraphAfter",
    "InsertParagraphBefore",
    "InsertTableAfter",
    "PageBreakSpec",
    "ParagraphSnapshot",
    "ParagraphSpec",
    "ReplaceParagraphText",
    "ReplaceTableCellText",
    "ReplaceTextMatch",
    "RenderDocumentRequest",
    "RenderDocumentResult",
    "RenderedPage",
    "RuntimeComponentStatus",
    "SearchDocumentRequest",
    "SearchDocumentResult",
    "TableCellSnapshot",
    "TableSnapshot",
    "TableSpec",
    "TextMatch",
    "TextRunSnapshot",
    "TextRunSpec",
    "UNSET",
    "UpdateParagraphProperties",
    "UpdateDocumentMetadata",
    "UpdateFooterText",
    "UpdateHeaderText",
    "UpdatePageSetup",
    "ValidateDocumentRequest",
    "ValidateDocumentResult",
    "ValidationIssue",
    "create_document",
    "edit_document",
    "inspect_document",
    "render_document",
    "search_document",
    "validate_document",
]
