"""与 Dashboard UI 无关的通用可观测契约与纯转换接口。

接入规则：普通工具以轻量 ToolDeclaration 共享 schema 和策略，再由运行时注册 handler；
能力目录只聚合声明快照；
后台组件可选发布 RuntimeComponentSnapshot；文件类结果可选发布 ArtifactRecord。
只有需要专用 UI 交互语义的模块才应注册 DashboardExtensionDescriptor，普通工具
和普通文件输出不需要反向依赖 Dashboard。
"""

from .artifacts import (
    ArtifactPublisher,
    ArtifactRecord,
    ArtifactStatus,
    ArtifactSummary,
    COMMON_ARTIFACT_KINDS,
    NullArtifactPublisher,
    project_artifact,
)
from .contracts import (
    CapabilityDescriptor,
    ModelCallObservation,
    NullObservationSink,
    ObservationSink,
    RunObservation,
    ToolCallObservation,
    ToolsetDescriptor,
    freeze_artifact_metadata,
    freeze_runtime_metadata,
)
from .extensions import DashboardExtensionDescriptor, DashboardExtensionRegistry
from .hooks import register_observation_sink
from .monitoring import (
    DEFAULT_MONITORING_PAGE_LIMIT,
    MAX_MONITORING_PAGE_LIMIT,
    ModelCallObservationView,
    MonitoringRecordInvalid,
    MonitoringRepositoryError,
    MonitoringRepositoryUnavailable,
    ObservationEventType,
    ObservationPage,
    ObservationQuery,
    ObservationReadRepository,
    ObservationSummary,
    RunObservationView,
    RunTimelineEntry,
    ToolCallObservationView,
    ToolExecutionPage,
    ToolExecutionQuery,
    ToolExecutionReadRepository,
)
from .monitoring_aggregation import (
    DEFAULT_MONITORING_WINDOW_SECONDS,
    MAX_MONITORING_TIME_BUCKETS,
    MAX_MONITORING_TOOL_STATS,
    MAX_MONITORING_WINDOW_SECONDS,
    FinishReasonCategory,
    FinishReasonCount,
    ModelCallMetrics,
    MonitoringAggregationQuery,
    MonitoringAggregationRepository,
    MonitoringGranularity,
    MonitoringOverview,
    MonitoringTimeBucket,
    MonitoringTimeSeries,
    MonitoringWindow,
    RunMetrics,
    ToolCallMetrics,
    ToolErrorCategory,
    ToolErrorCount,
    ToolExecutionMetrics,
    ToolStats,
    ToolStatsItem,
)
from .runtime import (
    NullRuntimeStatusPublisher,
    RuntimeComponentReporter,
    RuntimeComponentSnapshot,
    RuntimeComponentState,
    RuntimeStatusPublisher,
)
from .tool_execution import (
    ToolExecutionDetail,
    ToolExecutionSummary,
    project_tool_execution,
)


__all__ = [
    "ArtifactPublisher",
    "ArtifactRecord",
    "ArtifactStatus",
    "ArtifactSummary",
    "CapabilityDescriptor",
    "COMMON_ARTIFACT_KINDS",
    "DashboardExtensionDescriptor",
    "DashboardExtensionRegistry",
    "DEFAULT_MONITORING_PAGE_LIMIT",
    "DEFAULT_MONITORING_WINDOW_SECONDS",
    "FinishReasonCategory",
    "FinishReasonCount",
    "MAX_MONITORING_PAGE_LIMIT",
    "MAX_MONITORING_TIME_BUCKETS",
    "MAX_MONITORING_TOOL_STATS",
    "MAX_MONITORING_WINDOW_SECONDS",
    "ModelCallObservation",
    "ModelCallObservationView",
    "ModelCallMetrics",
    "MonitoringAggregationQuery",
    "MonitoringAggregationRepository",
    "MonitoringGranularity",
    "MonitoringOverview",
    "MonitoringRecordInvalid",
    "MonitoringRepositoryError",
    "MonitoringRepositoryUnavailable",
    "MonitoringTimeBucket",
    "MonitoringTimeSeries",
    "MonitoringWindow",
    "NullArtifactPublisher",
    "NullObservationSink",
    "NullRuntimeStatusPublisher",
    "ObservationSink",
    "ObservationEventType",
    "ObservationPage",
    "ObservationQuery",
    "ObservationReadRepository",
    "ObservationSummary",
    "RunObservation",
    "RunObservationView",
    "RunMetrics",
    "RunTimelineEntry",
    "RuntimeComponentReporter",
    "RuntimeComponentSnapshot",
    "RuntimeComponentState",
    "RuntimeStatusPublisher",
    "ToolCallObservation",
    "ToolCallObservationView",
    "ToolCallMetrics",
    "ToolErrorCategory",
    "ToolErrorCount",
    "ToolExecutionDetail",
    "ToolExecutionMetrics",
    "ToolExecutionPage",
    "ToolExecutionQuery",
    "ToolExecutionReadRepository",
    "ToolExecutionSummary",
    "ToolStats",
    "ToolStatsItem",
    "ToolsetDescriptor",
    "freeze_artifact_metadata",
    "freeze_runtime_metadata",
    "project_artifact",
    "project_tool_execution",
    "register_observation_sink",
]
